name: Telegram Bot Message

on:
  workflow_dispatch:  # Ye allow karta hai manually run karne ke liye
  schedule:
    - cron: '*/10 * * * *'  # Har 10 minute me run hoga (optional)

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Bot
        run: python main.py
